### ISSUE TITLE
CSV stringify doesn't escape commas

### ISSUE THREAD

**Issue by snomiao** [ricardobeat/TSV#6]
![image](https://user-images.githubusercontent.com/7323030/91116019-075e0b80-e6be-11ea-9678-a7eee4cd4289.png)

**Comment by ricardobeat** [comment]
@snomiao thanks a lot for opening an issue. I'd love to fix this but there are way better options for parsing CSV these days like [papaparse](http://ghub.io/papaparse); fixing this means writing an actual parser and I don't have a good reason to do that!

Clearly [this did not work](https://github.com/ricardobeat/TSV/commit/ac61fe2c0f7744100580d90e8b8c9781b4114f98), I'll add a deprecation notice to the README.
